// flow-typed signature: 46b1cf8c36bc9ffa58516a46e34bb7ef
// flow-typed version: <<STUB>>/cucumber-pretty_v^1.5.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cucumber-pretty'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cucumber-pretty' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'cucumber-pretty/index' {
  declare module.exports: $Exports<'cucumber-pretty'>;
}
declare module 'cucumber-pretty/index.js' {
  declare module.exports: $Exports<'cucumber-pretty'>;
}
