// flow-typed signature: 3d1ae226d7c7b7c6b05b18cb8d77f7d9
// flow-typed version: <<STUB>>/nightwatch-api_v^2.1.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nightwatch-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nightwatch-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nightwatch-api/lib/client' {
  declare module.exports: any;
}

declare module 'nightwatch-api/lib/index' {
  declare module.exports: any;
}

declare module 'nightwatch-api/lib/logger' {
  declare module.exports: any;
}

declare module 'nightwatch-api/lib/promisify' {
  declare module.exports: any;
}

declare module 'nightwatch-api/lib/proxy' {
  declare module.exports: any;
}

declare module 'nightwatch-api/lib/reporter' {
  declare module.exports: any;
}

declare module 'nightwatch-api/lib/screenshots' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nightwatch-api/lib/client.js' {
  declare module.exports: $Exports<'nightwatch-api/lib/client'>;
}
declare module 'nightwatch-api/lib/index.js' {
  declare module.exports: $Exports<'nightwatch-api/lib/index'>;
}
declare module 'nightwatch-api/lib/logger.js' {
  declare module.exports: $Exports<'nightwatch-api/lib/logger'>;
}
declare module 'nightwatch-api/lib/promisify.js' {
  declare module.exports: $Exports<'nightwatch-api/lib/promisify'>;
}
declare module 'nightwatch-api/lib/proxy.js' {
  declare module.exports: $Exports<'nightwatch-api/lib/proxy'>;
}
declare module 'nightwatch-api/lib/reporter.js' {
  declare module.exports: $Exports<'nightwatch-api/lib/reporter'>;
}
declare module 'nightwatch-api/lib/screenshots.js' {
  declare module.exports: $Exports<'nightwatch-api/lib/screenshots'>;
}
