// flow-typed signature: 091ccc59c8c03045cd17acfdfa8b4ba3
// flow-typed version: <<STUB>>/react-window-size_v^1.2.2/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-window-size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-window-size' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-window-size/dist/index' {
  declare module.exports: any;
}

declare module 'react-window-size/scripts/mocha_runner' {
  declare module.exports: any;
}

declare module 'react-window-size/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'react-window-size/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-window-size/dist/index.js' {
  declare module.exports: $Exports<'react-window-size/dist/index'>;
}
declare module 'react-window-size/index' {
  declare module.exports: $Exports<'react-window-size'>;
}
declare module 'react-window-size/index.js' {
  declare module.exports: $Exports<'react-window-size'>;
}
declare module 'react-window-size/scripts/mocha_runner.js' {
  declare module.exports: $Exports<'react-window-size/scripts/mocha_runner'>;
}
declare module 'react-window-size/src/__tests__/index.js' {
  declare module.exports: $Exports<'react-window-size/src/__tests__/index'>;
}
declare module 'react-window-size/src/index.js' {
  declare module.exports: $Exports<'react-window-size/src/index'>;
}
