// flow-typed signature: e345e097c3ea823013e368997b07787c
// flow-typed version: <<STUB>>/react-overlays_v^1.2.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-overlays'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-overlays' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-overlays/Affix' {
  declare module.exports: any;
}

declare module 'react-overlays/AutoAffix' {
  declare module.exports: any;
}

declare module 'react-overlays/Dropdown' {
  declare module.exports: any;
}

declare module 'react-overlays/DropdownContext' {
  declare module.exports: any;
}

declare module 'react-overlays/DropdownMenu' {
  declare module.exports: any;
}

declare module 'react-overlays/DropdownToggle' {
  declare module.exports: any;
}

declare module 'react-overlays/es/Affix' {
  declare module.exports: any;
}

declare module 'react-overlays/es/AutoAffix' {
  declare module.exports: any;
}

declare module 'react-overlays/es/Dropdown' {
  declare module.exports: any;
}

declare module 'react-overlays/es/DropdownContext' {
  declare module.exports: any;
}

declare module 'react-overlays/es/DropdownMenu' {
  declare module.exports: any;
}

declare module 'react-overlays/es/DropdownToggle' {
  declare module.exports: any;
}

declare module 'react-overlays/es/index' {
  declare module.exports: any;
}

declare module 'react-overlays/es/Modal' {
  declare module.exports: any;
}

declare module 'react-overlays/es/ModalManager' {
  declare module.exports: any;
}

declare module 'react-overlays/es/Overlay' {
  declare module.exports: any;
}

declare module 'react-overlays/es/Portal' {
  declare module.exports: any;
}

declare module 'react-overlays/es/RefHolder' {
  declare module.exports: any;
}

declare module 'react-overlays/es/RootCloseWrapper' {
  declare module.exports: any;
}

declare module 'react-overlays/es/utils/getContainer' {
  declare module.exports: any;
}

declare module 'react-overlays/es/utils/getDocumentHeight' {
  declare module.exports: any;
}

declare module 'react-overlays/es/utils/isOverflowing' {
  declare module.exports: any;
}

declare module 'react-overlays/es/utils/manageAriaHidden' {
  declare module.exports: any;
}

declare module 'react-overlays/es/utils/ownerDocument' {
  declare module.exports: any;
}

declare module 'react-overlays/es/utils/ownerWindow' {
  declare module.exports: any;
}

declare module 'react-overlays/es/WaitForContainer' {
  declare module.exports: any;
}

declare module 'react-overlays/Modal' {
  declare module.exports: any;
}

declare module 'react-overlays/ModalManager' {
  declare module.exports: any;
}

declare module 'react-overlays/Overlay' {
  declare module.exports: any;
}

declare module 'react-overlays/Portal' {
  declare module.exports: any;
}

declare module 'react-overlays/RefHolder' {
  declare module.exports: any;
}

declare module 'react-overlays/RootCloseWrapper' {
  declare module.exports: any;
}

declare module 'react-overlays/utils/getContainer' {
  declare module.exports: any;
}

declare module 'react-overlays/utils/getDocumentHeight' {
  declare module.exports: any;
}

declare module 'react-overlays/utils/isOverflowing' {
  declare module.exports: any;
}

declare module 'react-overlays/utils/manageAriaHidden' {
  declare module.exports: any;
}

declare module 'react-overlays/utils/ownerDocument' {
  declare module.exports: any;
}

declare module 'react-overlays/utils/ownerWindow' {
  declare module.exports: any;
}

declare module 'react-overlays/WaitForContainer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-overlays/Affix.js' {
  declare module.exports: $Exports<'react-overlays/Affix'>;
}
declare module 'react-overlays/AutoAffix.js' {
  declare module.exports: $Exports<'react-overlays/AutoAffix'>;
}
declare module 'react-overlays/Dropdown.js' {
  declare module.exports: $Exports<'react-overlays/Dropdown'>;
}
declare module 'react-overlays/DropdownContext.js' {
  declare module.exports: $Exports<'react-overlays/DropdownContext'>;
}
declare module 'react-overlays/DropdownMenu.js' {
  declare module.exports: $Exports<'react-overlays/DropdownMenu'>;
}
declare module 'react-overlays/DropdownToggle.js' {
  declare module.exports: $Exports<'react-overlays/DropdownToggle'>;
}
declare module 'react-overlays/es/Affix.js' {
  declare module.exports: $Exports<'react-overlays/es/Affix'>;
}
declare module 'react-overlays/es/AutoAffix.js' {
  declare module.exports: $Exports<'react-overlays/es/AutoAffix'>;
}
declare module 'react-overlays/es/Dropdown.js' {
  declare module.exports: $Exports<'react-overlays/es/Dropdown'>;
}
declare module 'react-overlays/es/DropdownContext.js' {
  declare module.exports: $Exports<'react-overlays/es/DropdownContext'>;
}
declare module 'react-overlays/es/DropdownMenu.js' {
  declare module.exports: $Exports<'react-overlays/es/DropdownMenu'>;
}
declare module 'react-overlays/es/DropdownToggle.js' {
  declare module.exports: $Exports<'react-overlays/es/DropdownToggle'>;
}
declare module 'react-overlays/es/index.js' {
  declare module.exports: $Exports<'react-overlays/es/index'>;
}
declare module 'react-overlays/es/Modal.js' {
  declare module.exports: $Exports<'react-overlays/es/Modal'>;
}
declare module 'react-overlays/es/ModalManager.js' {
  declare module.exports: $Exports<'react-overlays/es/ModalManager'>;
}
declare module 'react-overlays/es/Overlay.js' {
  declare module.exports: $Exports<'react-overlays/es/Overlay'>;
}
declare module 'react-overlays/es/Portal.js' {
  declare module.exports: $Exports<'react-overlays/es/Portal'>;
}
declare module 'react-overlays/es/RefHolder.js' {
  declare module.exports: $Exports<'react-overlays/es/RefHolder'>;
}
declare module 'react-overlays/es/RootCloseWrapper.js' {
  declare module.exports: $Exports<'react-overlays/es/RootCloseWrapper'>;
}
declare module 'react-overlays/es/utils/getContainer.js' {
  declare module.exports: $Exports<'react-overlays/es/utils/getContainer'>;
}
declare module 'react-overlays/es/utils/getDocumentHeight.js' {
  declare module.exports: $Exports<'react-overlays/es/utils/getDocumentHeight'>;
}
declare module 'react-overlays/es/utils/isOverflowing.js' {
  declare module.exports: $Exports<'react-overlays/es/utils/isOverflowing'>;
}
declare module 'react-overlays/es/utils/manageAriaHidden.js' {
  declare module.exports: $Exports<'react-overlays/es/utils/manageAriaHidden'>;
}
declare module 'react-overlays/es/utils/ownerDocument.js' {
  declare module.exports: $Exports<'react-overlays/es/utils/ownerDocument'>;
}
declare module 'react-overlays/es/utils/ownerWindow.js' {
  declare module.exports: $Exports<'react-overlays/es/utils/ownerWindow'>;
}
declare module 'react-overlays/es/WaitForContainer.js' {
  declare module.exports: $Exports<'react-overlays/es/WaitForContainer'>;
}
declare module 'react-overlays/index' {
  declare module.exports: $Exports<'react-overlays'>;
}
declare module 'react-overlays/index.js' {
  declare module.exports: $Exports<'react-overlays'>;
}
declare module 'react-overlays/Modal.js' {
  declare module.exports: $Exports<'react-overlays/Modal'>;
}
declare module 'react-overlays/ModalManager.js' {
  declare module.exports: $Exports<'react-overlays/ModalManager'>;
}
declare module 'react-overlays/Overlay.js' {
  declare module.exports: $Exports<'react-overlays/Overlay'>;
}
declare module 'react-overlays/Portal.js' {
  declare module.exports: $Exports<'react-overlays/Portal'>;
}
declare module 'react-overlays/RefHolder.js' {
  declare module.exports: $Exports<'react-overlays/RefHolder'>;
}
declare module 'react-overlays/RootCloseWrapper.js' {
  declare module.exports: $Exports<'react-overlays/RootCloseWrapper'>;
}
declare module 'react-overlays/utils/getContainer.js' {
  declare module.exports: $Exports<'react-overlays/utils/getContainer'>;
}
declare module 'react-overlays/utils/getDocumentHeight.js' {
  declare module.exports: $Exports<'react-overlays/utils/getDocumentHeight'>;
}
declare module 'react-overlays/utils/isOverflowing.js' {
  declare module.exports: $Exports<'react-overlays/utils/isOverflowing'>;
}
declare module 'react-overlays/utils/manageAriaHidden.js' {
  declare module.exports: $Exports<'react-overlays/utils/manageAriaHidden'>;
}
declare module 'react-overlays/utils/ownerDocument.js' {
  declare module.exports: $Exports<'react-overlays/utils/ownerDocument'>;
}
declare module 'react-overlays/utils/ownerWindow.js' {
  declare module.exports: $Exports<'react-overlays/utils/ownerWindow'>;
}
declare module 'react-overlays/WaitForContainer.js' {
  declare module.exports: $Exports<'react-overlays/WaitForContainer'>;
}
